"""initial_platform"""

import sqlalchemy as sa
from alembic import op

revision = "da6bd1560a9f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_accounts",
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('STUDENT','COUNSELLOR','ADMIN','RESEARCHER','SERVICE')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_version", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_case_id"), "audit_events", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_table(
        "workflow_cases",
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column("inference", sa.JSON(), nullable=True),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('RECEIVED','CONSENT_VERIFIED','PREPROCESSING','INFERENCE','EXPLANATION','READY_FOR_REVIEW','UNDER_REVIEW','COMPLETED','FAILED','WITHDRAWAL_REQUESTED','WITHDRAWN')"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("correlation_id"),
    )
    op.create_index(
        op.f("ix_workflow_cases_expires_at"), "workflow_cases", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_workflow_cases_status"), "workflow_cases", ["status"], unique=False)
    op.create_table(
        "access_sessions",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("access_jti", sa.String(length=36), nullable=False),
        sa.Column("refresh_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["access_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_jti"),
        sa.UniqueConstraint("refresh_hash"),
    )
    op.create_index(
        op.f("ix_access_sessions_account_id"), "access_sessions", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_access_sessions_family_id"), "access_sessions", ["family_id"], unique=False
    )
    op.create_table(
        "linkage_consents",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("purpose", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING','ACTIVE','EXPIRED','WITHDRAWN','REJECTED','INVALID')"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["access_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linkage_consents_account_id"), "linkage_consents", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_linkage_consents_expires_at"), "linkage_consents", ["expires_at"], unique=False
    )
    op.create_table(
        "linkage_withdrawals",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["workflow_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_table(
        "review_assignments",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("counsellor_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["workflow_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["counsellor_id"],
            ["access_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "counsellor_id"),
    )
    op.create_index(
        op.f("ix_review_assignments_case_id"), "review_assignments", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_assignments_counsellor_id"),
        "review_assignments",
        ["counsellor_id"],
        unique=False,
    )
    op.create_table(
        "review_tasks",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["workflow_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_table(
        "workflow_jobs",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("fixture_id", sa.String(length=20), nullable=True),
        sa.Column("idempotency_key", sa.String(length=36), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempts >= 0 AND attempts <= 3"),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["workflow_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_index(
        op.f("ix_workflow_jobs_lease_until"), "workflow_jobs", ["lease_until"], unique=False
    )
    op.create_index(op.f("ix_workflow_jobs_status"), "workflow_jobs", ["status"], unique=False)
    op.create_table(
        "workflow_retention",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["workflow_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_table(
        "linkage_cases",
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("consent_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["access_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["workflow_cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["linkage_consents.id"],
        ),
        sa.PrimaryKeyConstraint("case_id"),
        sa.UniqueConstraint("account_id", "idempotency_key"),
        sa.UniqueConstraint("consent_id"),
    )
    op.create_index(
        op.f("ix_linkage_cases_account_id"), "linkage_cases", ["account_id"], unique=False
    )
    op.create_table(
        "review_actions",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("idempotency_key", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["access_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["review_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_review_actions_task_id"), "review_actions", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_actions_task_id"), table_name="review_actions")
    op.drop_table("review_actions")
    op.drop_index(op.f("ix_linkage_cases_account_id"), table_name="linkage_cases")
    op.drop_table("linkage_cases")
    op.drop_table("workflow_retention")
    op.drop_index(op.f("ix_workflow_jobs_status"), table_name="workflow_jobs")
    op.drop_index(op.f("ix_workflow_jobs_lease_until"), table_name="workflow_jobs")
    op.drop_table("workflow_jobs")
    op.drop_table("review_tasks")
    op.drop_index(op.f("ix_review_assignments_counsellor_id"), table_name="review_assignments")
    op.drop_index(op.f("ix_review_assignments_case_id"), table_name="review_assignments")
    op.drop_table("review_assignments")
    op.drop_table("linkage_withdrawals")
    op.drop_index(op.f("ix_linkage_consents_expires_at"), table_name="linkage_consents")
    op.drop_index(op.f("ix_linkage_consents_account_id"), table_name="linkage_consents")
    op.drop_table("linkage_consents")
    op.drop_index(op.f("ix_access_sessions_family_id"), table_name="access_sessions")
    op.drop_index(op.f("ix_access_sessions_account_id"), table_name="access_sessions")
    op.drop_table("access_sessions")
    op.drop_index(op.f("ix_workflow_cases_status"), table_name="workflow_cases")
    op.drop_index(op.f("ix_workflow_cases_expires_at"), table_name="workflow_cases")
    op.drop_table("workflow_cases")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_case_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("access_accounts")
    # ### end Alembic commands ###
